### ISSUE TITLE
set-env command has been removed from github/actions and breaks build.

### ISSUE THREAD

**Issue by choffee** [puppetlabs/action-litmus_spec#59]
## Describe the Bug
Github have withdrawn the set-env command which is used by actions/core js package this seems to break things for running over the matrix of tests and we get the following error:

Error: Unable to process command '::set-env name=PUPPET_GEM_VERSION::~> 5.0' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

I think this is a bug in the upstream actions/core package as linked to below so will need to bump the version when that one is fixed.

## Expected Behavior
Test run without error.

## Steps to Reproduce
This is our actions file:
# This is a basic workflow to help you get started with Actions

```
name: CI

# Trigger the workflow on push or pull request
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  spec:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        check: [parallel_spec, 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop']
        ruby_version: [2.4.x,2.5.x]
        puppet_gem_version: [~> 5.0, ~> 6.0]
        exclude:
            # Don't repeat the linting on both puppet versions
          - puppet_gem_version: ~> 5.0
            check: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
            # Use ruby versions appropriate for the puppet version
          - ruby_version: 2.4.x
            puppet_gem_version: ~> 6.0
          - ruby_version: 2.5.x
            puppet_gem_version: ~> 5.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby_version}}
      - name: Spec Tests
        uses: puppetlabs/action-litmus_spec@master
        with:
          puppet_gem_version: ${{ matrix.puppet_gem_version }}
          check: ${{ matrix.check }}
```

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

## Additional Context
Upstream github action bug looks to be here:
https://github.com/actions/toolkit/issues/643
